export const onRequestPost = async ({ request, env }: any) => {
  const cors={'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type'}; if(request.method==='OPTIONS') return new Response('',{headers:cors});
  const body:any=await request.json().catch(()=>({})); const query=body.query||body.q||'Lagos business'; const location=body.location||{city:'Lagos',country:'Nigeria'}; const OPENAI_KEY=env.OPENAI_API_KEY;
  if(!OPENAI_KEY){ return new Response(JSON.stringify({query,location,summarizer:{summary:`${query} is high demand in ${location.city} with low competition. Great monetization potential.`,keyPoints:[`Demand for ${query} in ${location.city}`,`Low competition`,`High profit`],sentiment:'positive'},blueprint:{niche:query,targetAudience:`Residents of ${location.city}`,monetization:['Service fees','Ads','Affiliate','Subscription'],techStack:['React','Cloudflare','Pixabay']},buildGuide:{steps:[`Validate ${query} in ${location.city}`,`Build landing page`,`Add images/videos`,`Launch SEO`],tools:['engine-v1','Pixabay','Maps'],checklist:['Domain','Logo','Content','Launch']}}),{headers:cors}); }
  try { const call=async(p:string)=>{ const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{'Authorization':`Bearer ${OPENAI_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-4o-mini',messages:[{role:'user',content:p}],response_format:{type:'json_object'}})}).then(r=>r.json()); return JSON.parse(r.choices?.[0]?.message?.content||'{}'); };
    const summarizer=await call(`Analyze "${query}" in ${location.city}. Return JSON {summary:string,keyPoints:string[],sentiment:string}`); const blueprint=await call(`Based on ${JSON.stringify(summarizer)} for "${query}" in ${location.city}, return JSON {niche:string,targetAudience:string,monetization:string[],techStack:string[]}`); const buildGuide=await call(`For ${JSON.stringify(blueprint)} create JSON {steps:string[],tools:string[],checklist:string[]}`);
    return new Response(JSON.stringify({query,location,summarizer,blueprint,buildGuide}),{headers:cors});
  } catch(e:any){ return new Response(JSON.stringify({error:e.message}),{headers:cors,status:500}); }
}
export const onRequestOptions=async()=>new Response('',{headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type'}});
