import { useState, useEffect } from 'react';import { useSearchParams } from 'react-router-dom';
export default function SearchResults(){const [params]=useSearchParams();const qParam=params.get('q')||'FX rate USD/NGN';const [query,setQuery]=useState(qParam);const [input,setInput]=useState(qParam);const [tab,setTab]=useState<'all'|'web'|'videos'|'images'|'news'>('all');const [webData,setWebData]=useState<any>(null);const [vidData,setVidData]=useState<any>(null);const [imgData,setImgData]=useState<any>(null);const [newsData,setNewsData]=useState<any>(null);const [loadingWeb,setLoadingWeb]=useState(true);const [playing,setPlaying]=useState<string|null>(null);
useEffect(()=>{setLoadingWeb(true);setWebData(null);setVidData(null);setImgData(null);setNewsData(null);fetch(`/api/search?q=${encodeURIComponent(query)}`).then(r=>r.json()).then(j=>{setWebData(j);setLoadingWeb(false);}).catch(()=>setLoadingWeb(false));fetch(`/api/videos?q=${encodeURIComponent(query)}`).then(r=>r.json()).then(j=>setVidData(j)).catch(()=>{});fetch(`/api/images?q=${encodeURIComponent(query)}`).then(r=>r.json()).then(j=>setImgData(j)).catch(()=>{});fetch(`/api/news?q=${encodeURIComponent(query)}`).then(r=>r.json()).then(j=>setNewsData(j)).catch(()=>{});},[query]);
return (<div className="min-h-screen bg-[#0a0f14] text-zinc-200"><div className="max-w-[600px] mx-auto p-4 pb-24"><div className="flex gap-2 mb-4"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')setQuery(input)}} className="flex-1 bg-[#121a21] border border-zinc-700 rounded-full px-4 py-2.5 text-sm outline-none"/><button onClick={()=>setQuery(input)} className="bg-cyan-500 text-black px-5 rounded-full font-semibold">Go</button></div><div className="flex gap-2 mb-4 overflow-x-auto">{(['all','web','videos','images','news'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`px-4 py-1.5 rounded-full text-sm border shrink-0 ${tab===t?'bg-cyan-500 text-black border-cyan-500':'bg-[#121a21] border-zinc-700 text-zinc-400'}`}>{t.toUpperCase()}</button>)}</div>
{loadingWeb? (<div className="space-y-4 mt-6"><div className="p-4 bg-[#121a21] border border-zinc-800 rounded-2xl animate-pulse"><div className="h-3 w-24 bg-zinc-700 rounded mb-3"></div><div className="h-4 bg-zinc-800 rounded mb-2"></div><div className="h-4 bg-zinc-800 rounded w-5/6"></div></div><div className="h-20 bg-[#121a21] rounded-2xl animate-pulse"/><div className="text-zinc-600 text-sm text-center">Generating AI answer for "{query}"...</div></div>):
webData&&(<>
{/* GUARANTEED AI ANSWER - Always shows like Google/DuckDuckGo */}
{(tab==='all'||tab==='web')&& webData.summarizer && (
<div className="mb-6 p-4 bg-gradient-to-br from-[#121a21] to-[#0f1a1f] border border-cyan-900/30 rounded-2xl shadow-[0_0_20px_rgba(6,182,212,0.1)]">
  <div className="flex items-center gap-2 mb-3"><div className="text-[11px] tracking-widest text-cyan-400 font-bold">🧠 AI ANSWER • Instant • {webData.summarizer.source}</div>{webData.summarizer.guaranteed&&<span className="text-[9px] px-2 py-0.5 bg-cyan-950 text-cyan-400 rounded-full border border-cyan-900">GUARANTEED</span>}</div>
  <div className="text-[15px] leading-[1.7] text-zinc-100">{webData.summarizer.definition}</div>
  {webData.summarizer.wiki&&<div className="mt-3 pt-3 border-t border-zinc-800/50"><div className="text-[11px] text-zinc-500">Source: Wikipedia • <span className="text-cyan-400 cursor-pointer" onClick={()=>window.open(webData.summarizer.wiki.url,'_blank')}>{webData.summarizer.wiki.title}</span></div></div>}
  {webData.summarizer.coreIntelligence?.length>0&&<div className="mt-4 grid gap-2">{webData.summarizer.coreIntelligence.map((c:any,i:number)=><div key={i} className="flex gap-2 text-[12px]"><span className="text-cyan-500 font-mono">[{c.label}]</span><span className="text-zinc-400">{c.value}</span></div>)}</div>}
  <div className="mt-3 text-[10px] text-zinc-600">{webData.summarizer.engineProcess}</div>
</div>)}

{(tab==='all'||tab==='web')&&(<div className="mb-8"><div className="text-zinc-500 text-[12px] tracking-[0.2em] mb-4">🌐 WEB - {webData.web?.length} • Instant</div><div className="space-y-5">{webData.web?.map((r:any,i:number)=><div key={i} onClick={()=>window.open(r.url,'_blank')} className="cursor-pointer"><div className="flex gap-2 text-[11px] text-zinc-500"><img src={r.favicon} className="w-4 h-4 rounded-full bg-white" referrerPolicy="no-referrer"/>{r.displayUrl}</div><div className="text-cyan-400 font-semibold mt-1">{r.title}</div><div className="text-zinc-400 text-[13px] mt-1">{r.snippet}</div></div>)}</div></div>)}
{(tab==='all'||tab==='videos')&&(<div className="mb-8"><div className="text-zinc-500 text-[12px] tracking-[0.2em] mb-4">🎬 VIDEOS - {vidData?`${vidData.videos_total} real`: 'Loading...'}</div>{!vidData?<div className="h-32 bg-[#121a21] rounded-xl animate-pulse"/>:<div className="space-y-4">{vidData.videos?.slice(0,12).map((v:any,i:number)=><div key={i} className="rounded-xl overflow-hidden bg-[#121a21] border border-zinc-800">{playing===v.videoId?<iframe src={v.embed_url} className="w-full h-[200px]" allowFullScreen/>:<div className="relative cursor-pointer" onClick={()=>setPlaying(v.videoId)}><img src={v.thumbnail} className="w-full h-[190px] object-cover" referrerPolicy="no-referrer" loading="lazy"/><div className="absolute inset-0 flex items-center justify-center"><div className="w-12 h-12 rounded-full bg-white/90 flex items-center justify-center text-black">▶</div></div></div>}<div className="p-3 text-[14px] font-semibold">{v.title}</div></div>)}</div>}</div>)}
{(tab==='all'||tab==='images')&&(<div className="mb-8"><div className="text-zinc-500 text-[12px] tracking-[0.2em] mb-4">🖼️ IMAGES - {imgData?`${imgData.images_total} real`: 'Loading...'}</div>{!imgData?<div className="grid grid-cols-2 gap-2"><div className="h-32 bg-[#121a21] rounded-xl animate-pulse"/><div className="h-32 bg-[#121a21] rounded-xl animate-pulse"/></div>:<div className="grid grid-cols-2 gap-2">{imgData.images?.map((im:any,i:number)=><div key={i} className="rounded-xl overflow-hidden bg-[#121a21] border border-zinc-700"><img src={im.thumb} className="w-full h-[160px] object-cover" loading="lazy" referrerPolicy="no-referrer" onError={(e:any)=>{e.currentTarget.src=im.proxy||im.url}}/></div>)}</div>}</div>)}
{(tab==='all'||tab==='news')&&(<div className="mb-8"><div className="text-zinc-500 text-[12px] tracking-[0.2em] mb-4">📰 NEWS - {newsData?`${newsData.news_total}`:'Loading...'}</div>{!newsData?<div className="h-20 bg-[#121a21] rounded-xl animate-pulse"/>:<div className="space-y-4">{newsData.news?.map((n:any,i:number)=><div key={i} onClick={()=>window.open(n.url,'_blank')} className="cursor-pointer border-b border-zinc-800/50 pb-3"><div className="text-[11px] text-zinc-500">{n.domain}</div><div className="font-semibold mt-1">{n.title}</div></div>)}</div>}</div>)}
</>)}
</div></div>);}
